In [1]:
import gym
import math
import matplotlib.pyplot as plt

In [2]:
observations = []
env = gym.make("CartPole-v1")
env.reset()
done = False
while not done:
    observation, reward, done, info = env.step(0)
    observations.append(observation)
env.close()

c:\Users\pufan\.conda\envs\SC3000\lib\site-packages\gym\core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
c:\Users\pufan\.conda\envs\SC3000\lib\site-packages\gym\wrappers\step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
c:\Users\pufan\.conda\envs\SC3000\lib\site-packages\gym\utils\passive_env_checker.py:241: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


In [3]:
observations

[array([-0.00063759, -0.16367942, -0.00176525,  0.29616877], dtype=float32),
 array([-0.00391118, -0.35877615,  0.00415812,  0.58829445], dtype=float32),
 array([-0.0110867 , -0.5539561 ,  0.01592401,  0.8822843 ], dtype=float32),
 array([-0.02216582, -0.74929065,  0.0335697 ,  1.1799304 ], dtype=float32),
 array([-0.03715163, -0.94483197,  0.05716831,  1.4829448 ], dtype=float32),
 array([-0.05604827, -1.1406027 ,  0.0868272 ,  1.7929195 ], dtype=float32),
 array([-0.07886033, -1.3365839 ,  0.1226856 ,  2.1112788 ], dtype=float32),
 array([-0.105592  , -1.5327005 ,  0.16491117,  2.4392219 ], dtype=float32),
 array([-0.13624601, -1.7288053 ,  0.21369562,  2.7776527 ], dtype=float32)]

In [ ]:
x_s = [obs[0] for obs in observations]
theta_s = [math.tan(obs[2]) for obs in observations]

In [ ]:
plt.figure(figsize=(10, 5))
plt.plot(x_s, theta_s, label="Theta over X")
plt.xlabel("X position")
plt.ylabel("Theta (tan of pole angle)")
plt.title("Theta as a function of X position")
plt.legend()
plt.show()